name: WinICEPipeline 
trigger: none

pool:
  name: Default
  demands: Agent.Name -equals 136 Server 

resources:
  pipelines:
  - pipeline: WinICEPipeline  
    source: Build-AvoAssure
    trigger: true


steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: 'c5d3a8af-ebac-4015-ad8b-72c66fcf8fbd'
    pipeline: '182'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'dependencies'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CmdLine@2
  displayName: 'List Contents of dependencies directory'
  inputs:
    script: 'dir "$(Build.ArtifactStagingDirectory)\dependencies"'

- task: PowerShell@2
  displayName: 'Unzipping dependencies'
  inputs:
    targetType: 'inline'
    script: 'Expand-Archive -Path "$(Build.ArtifactStagingDirectory)\dependencies\dependencies.zip" -DestinationPath "$(Build.ArtifactStagingDirectory)"'

- script: |
    rmdir /s /q "$(Build.ArtifactStagingDirectory)\dependencies"
    dir $(System.ArtifactsDirectory)
  displayName: 'Listing directory'

- checkout: git://$(System.TeamProject)/ICE  #####
  persistCredentials: true
  clean: true
  path: s\avoassure

- task: CmdLine@2
  inputs:
    script: |
      #copy "$(System.ArtifactsDirectory)\BranchName.txt" "s\avoassure\"
      set /p BranchName=<"$(System.ArtifactsDirectory)\BranchName.txt"
      #set BranchName=$(cat $(System.ArtifactsDirectory)\BranchName.txt)
      echo "Branch Name is:%BranchName%"
      echo $(Build.SourceBranch)
      cd s\avoassure
      git checkout %BranchName%
      dir
  displayName: 'Setting Branch Name'

- task: PythonScript@0
  displayName: 'Running build python script'
  inputs:
    scriptPath: 'build/build_classic.py'

- script: |
   mkdir AvoAssure 
  displayName: 'Creating AvoAssure directory/folder'
 
- script: |
   cd assets 
   del update.py
   cd..
   move plugins AvoAssure
   move  assets AvoAssure
  displayName: 'Moving plugins and assets to AvoAssure folder'
 
- task: ArchiveFiles@2
  displayName: 'Archive AvoAssure'
  inputs:
    rootFolderOrFile: AvoAssure
    includeRootFolder: false
    archiveType: 7z
    archiveFile: '$(Build.ArtifactStagingDirectory)/AvoAssure.7z'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: dist'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/AvoAssure.7z'
    ArtifactName: dist