# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nineteen68' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftSocket'
	pod 'SwiftyJSON'

  # Pods for Nineteen68

  target 'Nineteen68UITests' do
    inherit! :search_paths
    # Pods for testing
	pod 'SwiftSocket'
	pod 'SwiftyJSON'
  end

end



