mobile_keywords={
    'getdate': 'mob_obj.Get_Date',
    'getselectednumber': 'mob_obj.Get_Selected_Number',
    'gettime': 'mob_obj.Get_Time',
    'selectnumber': 'mob_obj.Select_Number',
    'setdate': 'mob_obj.Set_Date',
    'setmaxvalue': 'mob_obj.Set_Max_Value',
    'setmidvalue': 'mob_obj.Set_Mid_Value',
    'setminvalue': 'mob_obj.Set_Min_Value',
    'settime': 'mob_obj.Set_Time',
    'verifyselectednumber': 'mob_obj.Verify_Selected_Number',
    'backpress': 'mob_obj.backPress',
    'cleartext': 'mob_obj.clear_text',
    'findcoordinateshorizontal': 'mob_obj.find_coordinates_horizontal',
    'findcoordinatesvertical': 'mob_obj.find_coordinates_vertical',
    'getmobileelement': 'mob_obj.getMobileElement',
    'getbuttonname': 'mob_obj.get_button_name',
    'getstatus': 'mob_obj.get_status',
    'gettext': 'mob_obj.get_text',
    'launchapplication': 'mob_obj.launch_application',
    'longpress': 'mob_obj.long_press',
    'press': 'mob_obj.press',
    'selectcheckbox': 'mob_obj.select_checkbox',
    'selectradiobutton': 'mob_obj.select_radio_button',
    'sendvalue': 'mob_obj.send_value',
    'settext': 'mob_obj.set_text',
    'startserver': 'mob_obj.start_server',
    'swipedown': 'mob_obj.swipe_down',
    'swipeleft': 'mob_obj.swipe_left',
    'swiperight': 'mob_obj.swipe_right',
    'swipeup': 'mob_obj.swipe_up',
    'toggleoff': 'mob_obj.toggle_off',
    'toggleon': 'mob_obj.toggle_on',
    'unselectcheckbox': 'mob_obj.unselect_checkbox',
    'verifybuttonname': 'mob_obj.verify_button_name',
    'verifydisabled': 'mob_obj.verify_disabled',
    'verifydoesnotexists': 'mob_obj.verify_does_not_exists',
    'verifyenabled': 'mob_obj.verify_enabled',
    'verifyexists': 'mob_obj.verify_exists',
    'verifyhidden': 'mob_obj.verify_hidden',
    'verifytext': 'mob_obj.verify_text',
    'verifyvisible': 'mob_obj.verify_visible',
    'waitforelementexists': 'mob_obj.waitforelement_exists',
    'getallvalues': 'spinner_obj.get_all_values',
    'getcount': 'spinner_obj.get_count',
    'getmultiplevaluesbyindexs': 'spinner_obj.get_multiple_values_by_indexs',
    'getselectedvalue': 'spinner_obj.get_selected_value',
    'getvaluebyindex': 'spinner_obj.get_value_by_index',
    'selectmultiplevaluebyindex': 'spinner_obj.select_multiple_value_by_index',
    'selectmultiplevaluebytext': 'spinner_obj.select_multiple_value_by_text',
    'selectvaluebyindex': 'spinner_obj.select_value_by_index',
    'selectvaluebytext': 'spinner_obj.select_value_by_text',
    'verifyallvalues': 'spinner_obj.verify_all_values',
    'verifycount': 'spinner_obj.verify_count',
    'verifyselectedvalue': 'spinner_obj.verify_selected_value',
    'setsecuretext': 'mob_obj.set_secure_text',
    'hidesoftkeyboard': 'mob_obj.hide_soft_keyboard'
}

generic_keywords={
 'createdynvariable': 'gen_obj.create_dynamic_variable',
 'wait': 'gen_obj.wait'
}

aws_supported_keywords=list(mobile_keywords.keys())
aws_supported_keywords.extend(list(generic_keywords.keys()))
